/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Sport = IDL.Variant({
  'basketball' : IDL.Null,
  'football' : IDL.Null,
  'both' : IDL.Null,
});
export const AchievementCategory = IDL.Variant({
  'award' : IDL.Null,
  'milestone' : IDL.Null,
  'gameStat' : IDL.Null,
});
export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'sport' : Sport,
  'stats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'category' : AchievementCategory,
});
export const PostStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'draft' : IDL.Null,
  'posted' : IDL.Null,
});
export const SocialPlatform = IDL.Variant({
  'all' : IDL.Null,
  'twitter' : IDL.Null,
  'instagram' : IDL.Null,
  'facebook' : IDL.Null,
});
export const ContentPost = IDL.Record({
  'id' : IDL.Nat,
  'status' : PostStatus,
  'achievementId' : IDL.Opt(IDL.Nat),
  'hashtags' : IDL.Vec(IDL.Text),
  'scheduledDate' : IDL.Opt(Time),
  'platform' : SocialPlatform,
  'caption' : IDL.Text,
  'mediaUrls' : IDL.Vec(IDL.Text),
});
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ScholarshipStatus = IDL.Variant({
  'researching' : IDL.Null,
  'applied' : IDL.Null,
  'committed' : IDL.Null,
  'visited' : IDL.Null,
  'contacted' : IDL.Null,
  'declined' : IDL.Null,
  'offered' : IDL.Null,
  'interested' : IDL.Null,
});
export const CollegeDivision = IDL.Variant({
  'd1' : IDL.Null,
  'd2' : IDL.Null,
  'd3' : IDL.Null,
  'juco' : IDL.Null,
  'naia' : IDL.Null,
});
export const ScholarshipTarget = IDL.Record({
  'id' : IDL.Nat,
  'status' : ScholarshipStatus,
  'coachEmail' : IDL.Text,
  'collegeName' : IDL.Text,
  'division' : CollegeDivision,
  'coachPhone' : IDL.Text,
  'sport' : Sport,
  'notes' : IDL.Text,
  'lastContactDate' : Time,
  'coachName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AthleteProfile = IDL.Record({
  'bio' : IDL.Text,
  'gpa' : IDL.Text,
  'weight' : IDL.Text,
  'height' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'graduationYear' : IDL.Nat,
  'sport' : Sport,
  'state' : IDL.Text,
  'hudlLink' : IDL.Text,
  'twitterHandle' : IDL.Text,
  'position' : IDL.Text,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'caption' : IDL.Text,
  'mediaType' : MediaType,
  'uploadDate' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAchievement' : IDL.Func([Achievement], [IDL.Nat], []),
  'addContentPost' : IDL.Func([ContentPost], [IDL.Nat], []),
  'addMediaItem' : IDL.Func(
      [MediaType, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'addScholarshipTarget' : IDL.Func([ScholarshipTarget], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAchievement' : IDL.Func([IDL.Nat], [], []),
  'deleteContentPost' : IDL.Func([IDL.Nat], [], []),
  'deleteMediaItem' : IDL.Func([IDL.Nat], [], []),
  'deleteScholarshipTarget' : IDL.Func([IDL.Nat], [], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getAthleteProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AthleteProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AthleteProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentPosts' : IDL.Func([], [IDL.Vec(ContentPost)], ['query']),
  'getMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getScholarshipTargets' : IDL.Func(
      [],
      [IDL.Vec(ScholarshipTarget)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AthleteProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAthleteProfile' : IDL.Func([AthleteProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([AthleteProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Sport = IDL.Variant({
    'basketball' : IDL.Null,
    'football' : IDL.Null,
    'both' : IDL.Null,
  });
  const AchievementCategory = IDL.Variant({
    'award' : IDL.Null,
    'milestone' : IDL.Null,
    'gameStat' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'sport' : Sport,
    'stats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'category' : AchievementCategory,
  });
  const PostStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'draft' : IDL.Null,
    'posted' : IDL.Null,
  });
  const SocialPlatform = IDL.Variant({
    'all' : IDL.Null,
    'twitter' : IDL.Null,
    'instagram' : IDL.Null,
    'facebook' : IDL.Null,
  });
  const ContentPost = IDL.Record({
    'id' : IDL.Nat,
    'status' : PostStatus,
    'achievementId' : IDL.Opt(IDL.Nat),
    'hashtags' : IDL.Vec(IDL.Text),
    'scheduledDate' : IDL.Opt(Time),
    'platform' : SocialPlatform,
    'caption' : IDL.Text,
    'mediaUrls' : IDL.Vec(IDL.Text),
  });
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ScholarshipStatus = IDL.Variant({
    'researching' : IDL.Null,
    'applied' : IDL.Null,
    'committed' : IDL.Null,
    'visited' : IDL.Null,
    'contacted' : IDL.Null,
    'declined' : IDL.Null,
    'offered' : IDL.Null,
    'interested' : IDL.Null,
  });
  const CollegeDivision = IDL.Variant({
    'd1' : IDL.Null,
    'd2' : IDL.Null,
    'd3' : IDL.Null,
    'juco' : IDL.Null,
    'naia' : IDL.Null,
  });
  const ScholarshipTarget = IDL.Record({
    'id' : IDL.Nat,
    'status' : ScholarshipStatus,
    'coachEmail' : IDL.Text,
    'collegeName' : IDL.Text,
    'division' : CollegeDivision,
    'coachPhone' : IDL.Text,
    'sport' : Sport,
    'notes' : IDL.Text,
    'lastContactDate' : Time,
    'coachName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AthleteProfile = IDL.Record({
    'bio' : IDL.Text,
    'gpa' : IDL.Text,
    'weight' : IDL.Text,
    'height' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'graduationYear' : IDL.Nat,
    'sport' : Sport,
    'state' : IDL.Text,
    'hudlLink' : IDL.Text,
    'twitterHandle' : IDL.Text,
    'position' : IDL.Text,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'caption' : IDL.Text,
    'mediaType' : MediaType,
    'uploadDate' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAchievement' : IDL.Func([Achievement], [IDL.Nat], []),
    'addContentPost' : IDL.Func([ContentPost], [IDL.Nat], []),
    'addMediaItem' : IDL.Func(
        [MediaType, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'addScholarshipTarget' : IDL.Func([ScholarshipTarget], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAchievement' : IDL.Func([IDL.Nat], [], []),
    'deleteContentPost' : IDL.Func([IDL.Nat], [], []),
    'deleteMediaItem' : IDL.Func([IDL.Nat], [], []),
    'deleteScholarshipTarget' : IDL.Func([IDL.Nat], [], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getAthleteProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AthleteProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AthleteProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentPosts' : IDL.Func([], [IDL.Vec(ContentPost)], ['query']),
    'getMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getScholarshipTargets' : IDL.Func(
        [],
        [IDL.Vec(ScholarshipTarget)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AthleteProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAthleteProfile' : IDL.Func([AthleteProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([AthleteProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };