/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'description' : string,
  'sport' : Sport,
  'stats' : Array<[string, string]>,
  'category' : AchievementCategory,
}
export type AchievementCategory = { 'award' : null } |
  { 'milestone' : null } |
  { 'gameStat' : null };
export interface AthleteProfile {
  'bio' : string,
  'gpa' : string,
  'weight' : string,
  'height' : string,
  'city' : string,
  'name' : string,
  'instagramHandle' : string,
  'graduationYear' : bigint,
  'sport' : Sport,
  'state' : string,
  'hudlLink' : string,
  'twitterHandle' : string,
  'position' : string,
}
export type CollegeDivision = { 'd1' : null } |
  { 'd2' : null } |
  { 'd3' : null } |
  { 'juco' : null } |
  { 'naia' : null };
export interface ContentPost {
  'id' : bigint,
  'status' : PostStatus,
  'achievementId' : [] | [bigint],
  'hashtags' : Array<string>,
  'scheduledDate' : [] | [Time],
  'platform' : SocialPlatform,
  'caption' : string,
  'mediaUrls' : Array<string>,
}
export type ExternalBlob = Uint8Array;
export interface MediaItem {
  'id' : bigint,
  'blob' : ExternalBlob,
  'tags' : Array<string>,
  'caption' : string,
  'mediaType' : MediaType,
  'uploadDate' : Time,
}
export type MediaType = { 'video' : null } |
  { 'photo' : null };
export type PostStatus = { 'scheduled' : null } |
  { 'draft' : null } |
  { 'posted' : null };
export type ScholarshipStatus = { 'researching' : null } |
  { 'applied' : null } |
  { 'committed' : null } |
  { 'visited' : null } |
  { 'contacted' : null } |
  { 'declined' : null } |
  { 'offered' : null } |
  { 'interested' : null };
export interface ScholarshipTarget {
  'id' : bigint,
  'status' : ScholarshipStatus,
  'coachEmail' : string,
  'collegeName' : string,
  'division' : CollegeDivision,
  'coachPhone' : string,
  'sport' : Sport,
  'notes' : string,
  'lastContactDate' : Time,
  'coachName' : string,
}
export type SocialPlatform = { 'all' : null } |
  { 'twitter' : null } |
  { 'instagram' : null } |
  { 'facebook' : null };
export type Sport = { 'basketball' : null } |
  { 'football' : null } |
  { 'both' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAchievement' : ActorMethod<[Achievement], bigint>,
  'addContentPost' : ActorMethod<[ContentPost], bigint>,
  'addMediaItem' : ActorMethod<
    [MediaType, string, Array<string>, ExternalBlob],
    bigint
  >,
  'addScholarshipTarget' : ActorMethod<[ScholarshipTarget], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAchievement' : ActorMethod<[bigint], undefined>,
  'deleteContentPost' : ActorMethod<[bigint], undefined>,
  'deleteMediaItem' : ActorMethod<[bigint], undefined>,
  'deleteScholarshipTarget' : ActorMethod<[bigint], undefined>,
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  'getAthleteProfile' : ActorMethod<[Principal], [] | [AthleteProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [AthleteProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentPosts' : ActorMethod<[], Array<ContentPost>>,
  'getMediaItems' : ActorMethod<[], Array<MediaItem>>,
  'getScholarshipTargets' : ActorMethod<[], Array<ScholarshipTarget>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [AthleteProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAthleteProfile' : ActorMethod<[AthleteProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[AthleteProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];