/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScholarshipTarget {
    id: bigint;
    status: ScholarshipStatus;
    coachEmail: string;
    collegeName: string;
    division: CollegeDivision;
    coachPhone: string;
    sport: Sport;
    notes: string;
    lastContactDate: Time;
    coachName: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MediaItem {
    id: bigint;
    blob: ExternalBlob;
    tags: Array<string>;
    caption: string;
    mediaType: MediaType;
    uploadDate: Time;
}
export interface Achievement {
    id: bigint;
    title: string;
    date: Time;
    description: string;
    sport: Sport;
    stats: Array<[string, string]>;
    category: AchievementCategory;
}
export interface AthleteProfile {
    bio: string;
    gpa: string;
    weight: string;
    height: string;
    city: string;
    name: string;
    instagramHandle: string;
    graduationYear: bigint;
    sport: Sport;
    state: string;
    hudlLink: string;
    twitterHandle: string;
    position: string;
}
export interface ContentPost {
    id: bigint;
    status: PostStatus;
    achievementId?: bigint;
    hashtags: Array<string>;
    scheduledDate?: Time;
    platform: SocialPlatform;
    caption: string;
    mediaUrls: Array<string>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AchievementCategory {
    award = "award",
    milestone = "milestone",
    gameStat = "gameStat"
}
export enum CollegeDivision {
    d1 = "d1",
    d2 = "d2",
    d3 = "d3",
    juco = "juco",
    naia = "naia"
}
export enum MediaType {
    video = "video",
    photo = "photo"
}
export enum PostStatus {
    scheduled = "scheduled",
    draft = "draft",
    posted = "posted"
}
export enum ScholarshipStatus {
    researching = "researching",
    applied = "applied",
    committed = "committed",
    visited = "visited",
    contacted = "contacted",
    declined = "declined",
    offered = "offered",
    interested = "interested"
}
export enum SocialPlatform {
    all = "all",
    twitter = "twitter",
    instagram = "instagram",
    facebook = "facebook"
}
export enum Sport {
    basketball = "basketball",
    football = "football",
    both = "both"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAchievement(a: Achievement): Promise<bigint>;
    addContentPost(p: ContentPost): Promise<bigint>;
    addMediaItem(mediaType: MediaType, caption: string, tags: Array<string>, blob: ExternalBlob): Promise<bigint>;
    addScholarshipTarget(s: ScholarshipTarget): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAchievement(id: bigint): Promise<void>;
    deleteContentPost(id: bigint): Promise<void>;
    deleteMediaItem(id: bigint): Promise<void>;
    deleteScholarshipTarget(id: bigint): Promise<void>;
    getAchievements(): Promise<Array<Achievement>>;
    getAthleteProfile(user: Principal): Promise<AthleteProfile | null>;
    getCallerUserProfile(): Promise<AthleteProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContentPosts(): Promise<Array<ContentPost>>;
    getMediaItems(): Promise<Array<MediaItem>>;
    getScholarshipTargets(): Promise<Array<ScholarshipTarget>>;
    getUserProfile(user: Principal): Promise<AthleteProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveAthleteProfile(p: AthleteProfile): Promise<void>;
    saveCallerUserProfile(p: AthleteProfile): Promise<void>;
}
import type { Achievement as _Achievement, AchievementCategory as _AchievementCategory, AthleteProfile as _AthleteProfile, CollegeDivision as _CollegeDivision, ContentPost as _ContentPost, ExternalBlob as _ExternalBlob, MediaItem as _MediaItem, MediaType as _MediaType, PostStatus as _PostStatus, ScholarshipStatus as _ScholarshipStatus, ScholarshipTarget as _ScholarshipTarget, SocialPlatform as _SocialPlatform, Sport as _Sport, Time as _Time, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAchievement(arg0: Achievement): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAchievement(to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAchievement(to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addContentPost(arg0: ContentPost): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addContentPost(to_candid_ContentPost_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContentPost(to_candid_ContentPost_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMediaItem(arg0: MediaType, arg1: string, arg2: Array<string>, arg3: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaItem(to_candid_MediaType_n20(this._uploadFile, this._downloadFile, arg0), arg1, arg2, await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaItem(to_candid_MediaType_n20(this._uploadFile, this._downloadFile, arg0), arg1, arg2, await to_candid_ExternalBlob_n22(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addScholarshipTarget(arg0: ScholarshipTarget): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addScholarshipTarget(to_candid_ScholarshipTarget_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScholarshipTarget(to_candid_ScholarshipTarget_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAchievement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAchievement(arg0);
            return result;
        }
    }
    async deleteContentPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentPost(arg0);
            return result;
        }
    }
    async deleteMediaItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaItem(arg0);
            return result;
        }
    }
    async deleteScholarshipTarget(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScholarshipTarget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScholarshipTarget(arg0);
            return result;
        }
    }
    async getAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAthleteProfile(arg0: Principal): Promise<AthleteProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAthleteProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAthleteProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<AthleteProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentPosts(): Promise<Array<ContentPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentPosts();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentPosts();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaItems(): Promise<Array<MediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaItems();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaItems();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScholarshipTargets(): Promise<Array<ScholarshipTarget>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScholarshipTargets();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScholarshipTargets();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<AthleteProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveAthleteProfile(arg0: AthleteProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAthleteProfile(to_candid_AthleteProfile_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAthleteProfile(to_candid_AthleteProfile_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: AthleteProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_AthleteProfile_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_AthleteProfile_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AchievementCategory_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementCategory): AchievementCategory {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Achievement_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Achievement {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_AthleteProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AthleteProfile): AthleteProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_CollegeDivision_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollegeDivision): CollegeDivision {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_ContentPost_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentPost): ContentPost {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MediaItem_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaItem): Promise<MediaItem> {
    return await from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_PostStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_ScholarshipStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScholarshipStatus): ScholarshipStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_ScholarshipTarget_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScholarshipTarget): ScholarshipTarget {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_SocialPlatform_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialPlatform): SocialPlatform {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AthleteProfile]): AthleteProfile | null {
    return value.length === 0 ? null : from_candid_AthleteProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: _Time;
    description: string;
    sport: _Sport;
    stats: Array<[string, string]>;
    category: _AchievementCategory;
}): {
    id: bigint;
    title: string;
    date: Time;
    description: string;
    sport: Sport;
    stats: Array<[string, string]>;
    category: AchievementCategory;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        sport: from_candid_Sport_n34(_uploadFile, _downloadFile, value.sport),
        stats: value.stats,
        category: from_candid_AchievementCategory_n36(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    gpa: string;
    weight: string;
    height: string;
    city: string;
    name: string;
    instagramHandle: string;
    graduationYear: bigint;
    sport: _Sport;
    state: string;
    hudlLink: string;
    twitterHandle: string;
    position: string;
}): {
    bio: string;
    gpa: string;
    weight: string;
    height: string;
    city: string;
    name: string;
    instagramHandle: string;
    graduationYear: bigint;
    sport: Sport;
    state: string;
    hudlLink: string;
    twitterHandle: string;
    position: string;
} {
    return {
        bio: value.bio,
        gpa: value.gpa,
        weight: value.weight,
        height: value.height,
        city: value.city,
        name: value.name,
        instagramHandle: value.instagramHandle,
        graduationYear: value.graduationYear,
        sport: from_candid_Sport_n34(_uploadFile, _downloadFile, value.sport),
        state: value.state,
        hudlLink: value.hudlLink,
        twitterHandle: value.twitterHandle,
        position: value.position
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PostStatus;
    achievementId: [] | [bigint];
    hashtags: Array<string>;
    scheduledDate: [] | [_Time];
    platform: _SocialPlatform;
    caption: string;
    mediaUrls: Array<string>;
}): {
    id: bigint;
    status: PostStatus;
    achievementId?: bigint;
    hashtags: Array<string>;
    scheduledDate?: Time;
    platform: SocialPlatform;
    caption: string;
    mediaUrls: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_PostStatus_n46(_uploadFile, _downloadFile, value.status),
        achievementId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.achievementId)),
        hashtags: value.hashtags,
        scheduledDate: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.scheduledDate)),
        platform: from_candid_SocialPlatform_n49(_uploadFile, _downloadFile, value.platform),
        caption: value.caption,
        mediaUrls: value.mediaUrls
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: _ExternalBlob;
    tags: Array<string>;
    caption: string;
    mediaType: _MediaType;
    uploadDate: _Time;
}): Promise<{
    id: bigint;
    blob: ExternalBlob;
    tags: Array<string>;
    caption: string;
    mediaType: MediaType;
    uploadDate: Time;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n54(_uploadFile, _downloadFile, value.blob),
        tags: value.tags,
        caption: value.caption,
        mediaType: from_candid_MediaType_n55(_uploadFile, _downloadFile, value.mediaType),
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ScholarshipStatus;
    coachEmail: string;
    collegeName: string;
    division: _CollegeDivision;
    coachPhone: string;
    sport: _Sport;
    notes: string;
    lastContactDate: _Time;
    coachName: string;
}): {
    id: bigint;
    status: ScholarshipStatus;
    coachEmail: string;
    collegeName: string;
    division: CollegeDivision;
    coachPhone: string;
    sport: Sport;
    notes: string;
    lastContactDate: Time;
    coachName: string;
} {
    return {
        id: value.id,
        status: from_candid_ScholarshipStatus_n60(_uploadFile, _downloadFile, value.status),
        coachEmail: value.coachEmail,
        collegeName: value.collegeName,
        division: from_candid_CollegeDivision_n62(_uploadFile, _downloadFile, value.division),
        coachPhone: value.coachPhone,
        sport: from_candid_Sport_n34(_uploadFile, _downloadFile, value.sport),
        notes: value.notes,
        lastContactDate: value.lastContactDate,
        coachName: value.coachName
    };
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    basketball: null;
} | {
    football: null;
} | {
    both: null;
}): Sport {
    return "basketball" in value ? Sport.basketball : "football" in value ? Sport.football : "both" in value ? Sport.both : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    award: null;
} | {
    milestone: null;
} | {
    gameStat: null;
}): AchievementCategory {
    return "award" in value ? AchievementCategory.award : "milestone" in value ? AchievementCategory.milestone : "gameStat" in value ? AchievementCategory.gameStat : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    draft: null;
} | {
    posted: null;
}): PostStatus {
    return "scheduled" in value ? PostStatus.scheduled : "draft" in value ? PostStatus.draft : "posted" in value ? PostStatus.posted : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    twitter: null;
} | {
    instagram: null;
} | {
    facebook: null;
}): SocialPlatform {
    return "all" in value ? SocialPlatform.all : "twitter" in value ? SocialPlatform.twitter : "instagram" in value ? SocialPlatform.instagram : "facebook" in value ? SocialPlatform.facebook : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    photo: null;
}): MediaType {
    return "video" in value ? MediaType.video : "photo" in value ? MediaType.photo : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    researching: null;
} | {
    applied: null;
} | {
    committed: null;
} | {
    visited: null;
} | {
    contacted: null;
} | {
    declined: null;
} | {
    offered: null;
} | {
    interested: null;
}): ScholarshipStatus {
    return "researching" in value ? ScholarshipStatus.researching : "applied" in value ? ScholarshipStatus.applied : "committed" in value ? ScholarshipStatus.committed : "visited" in value ? ScholarshipStatus.visited : "contacted" in value ? ScholarshipStatus.contacted : "declined" in value ? ScholarshipStatus.declined : "offered" in value ? ScholarshipStatus.offered : "interested" in value ? ScholarshipStatus.interested : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    d1: null;
} | {
    d2: null;
} | {
    d3: null;
} | {
    juco: null;
} | {
    naia: null;
}): CollegeDivision {
    return "d1" in value ? CollegeDivision.d1 : "d2" in value ? CollegeDivision.d2 : "d3" in value ? CollegeDivision.d3 : "juco" in value ? CollegeDivision.juco : "naia" in value ? CollegeDivision.naia : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Array<Achievement> {
    return value.map((x)=>from_candid_Achievement_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentPost>): Array<ContentPost> {
    return value.map((x)=>from_candid_ContentPost_n44(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaItem>): Promise<Array<MediaItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MediaItem_n52(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScholarshipTarget>): Array<ScholarshipTarget> {
    return value.map((x)=>from_candid_ScholarshipTarget_n58(_uploadFile, _downloadFile, x));
}
function to_candid_AchievementCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AchievementCategory): _AchievementCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Achievement_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Achievement): _Achievement {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_AthleteProfile_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AthleteProfile): _AthleteProfile {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_CollegeDivision_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollegeDivision): _CollegeDivision {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_ContentPost_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentPost): _ContentPost {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MediaType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_PostStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): _PostStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ScholarshipStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScholarshipStatus): _ScholarshipStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_ScholarshipTarget_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScholarshipTarget): _ScholarshipTarget {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_SocialPlatform_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialPlatform): _SocialPlatform {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Sport_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): _Sport {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: PostStatus;
    achievementId?: bigint;
    hashtags: Array<string>;
    scheduledDate?: Time;
    platform: SocialPlatform;
    caption: string;
    mediaUrls: Array<string>;
}): {
    id: bigint;
    status: _PostStatus;
    achievementId: [] | [bigint];
    hashtags: Array<string>;
    scheduledDate: [] | [_Time];
    platform: _SocialPlatform;
    caption: string;
    mediaUrls: Array<string>;
} {
    return {
        id: value.id,
        status: to_candid_PostStatus_n16(_uploadFile, _downloadFile, value.status),
        achievementId: value.achievementId ? candid_some(value.achievementId) : candid_none(),
        hashtags: value.hashtags,
        scheduledDate: value.scheduledDate ? candid_some(value.scheduledDate) : candid_none(),
        platform: to_candid_SocialPlatform_n18(_uploadFile, _downloadFile, value.platform),
        caption: value.caption,
        mediaUrls: value.mediaUrls
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ScholarshipStatus;
    coachEmail: string;
    collegeName: string;
    division: CollegeDivision;
    coachPhone: string;
    sport: Sport;
    notes: string;
    lastContactDate: Time;
    coachName: string;
}): {
    id: bigint;
    status: _ScholarshipStatus;
    coachEmail: string;
    collegeName: string;
    division: _CollegeDivision;
    coachPhone: string;
    sport: _Sport;
    notes: string;
    lastContactDate: _Time;
    coachName: string;
} {
    return {
        id: value.id,
        status: to_candid_ScholarshipStatus_n25(_uploadFile, _downloadFile, value.status),
        coachEmail: value.coachEmail,
        collegeName: value.collegeName,
        division: to_candid_CollegeDivision_n27(_uploadFile, _downloadFile, value.division),
        coachPhone: value.coachPhone,
        sport: to_candid_Sport_n10(_uploadFile, _downloadFile, value.sport),
        notes: value.notes,
        lastContactDate: value.lastContactDate,
        coachName: value.coachName
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    gpa: string;
    weight: string;
    height: string;
    city: string;
    name: string;
    instagramHandle: string;
    graduationYear: bigint;
    sport: Sport;
    state: string;
    hudlLink: string;
    twitterHandle: string;
    position: string;
}): {
    bio: string;
    gpa: string;
    weight: string;
    height: string;
    city: string;
    name: string;
    instagramHandle: string;
    graduationYear: bigint;
    sport: _Sport;
    state: string;
    hudlLink: string;
    twitterHandle: string;
    position: string;
} {
    return {
        bio: value.bio,
        gpa: value.gpa,
        weight: value.weight,
        height: value.height,
        city: value.city,
        name: value.name,
        instagramHandle: value.instagramHandle,
        graduationYear: value.graduationYear,
        sport: to_candid_Sport_n10(_uploadFile, _downloadFile, value.sport),
        state: value.state,
        hudlLink: value.hudlLink,
        twitterHandle: value.twitterHandle,
        position: value.position
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: Time;
    description: string;
    sport: Sport;
    stats: Array<[string, string]>;
    category: AchievementCategory;
}): {
    id: bigint;
    title: string;
    date: _Time;
    description: string;
    sport: _Sport;
    stats: Array<[string, string]>;
    category: _AchievementCategory;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        sport: to_candid_Sport_n10(_uploadFile, _downloadFile, value.sport),
        stats: value.stats,
        category: to_candid_AchievementCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): {
    basketball: null;
} | {
    football: null;
} | {
    both: null;
} {
    return value == Sport.basketball ? {
        basketball: null
    } : value == Sport.football ? {
        football: null
    } : value == Sport.both ? {
        both: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AchievementCategory): {
    award: null;
} | {
    milestone: null;
} | {
    gameStat: null;
} {
    return value == AchievementCategory.award ? {
        award: null
    } : value == AchievementCategory.milestone ? {
        milestone: null
    } : value == AchievementCategory.gameStat ? {
        gameStat: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): {
    scheduled: null;
} | {
    draft: null;
} | {
    posted: null;
} {
    return value == PostStatus.scheduled ? {
        scheduled: null
    } : value == PostStatus.draft ? {
        draft: null
    } : value == PostStatus.posted ? {
        posted: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialPlatform): {
    all: null;
} | {
    twitter: null;
} | {
    instagram: null;
} | {
    facebook: null;
} {
    return value == SocialPlatform.all ? {
        all: null
    } : value == SocialPlatform.twitter ? {
        twitter: null
    } : value == SocialPlatform.instagram ? {
        instagram: null
    } : value == SocialPlatform.facebook ? {
        facebook: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    video: null;
} | {
    photo: null;
} {
    return value == MediaType.video ? {
        video: null
    } : value == MediaType.photo ? {
        photo: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScholarshipStatus): {
    researching: null;
} | {
    applied: null;
} | {
    committed: null;
} | {
    visited: null;
} | {
    contacted: null;
} | {
    declined: null;
} | {
    offered: null;
} | {
    interested: null;
} {
    return value == ScholarshipStatus.researching ? {
        researching: null
    } : value == ScholarshipStatus.applied ? {
        applied: null
    } : value == ScholarshipStatus.committed ? {
        committed: null
    } : value == ScholarshipStatus.visited ? {
        visited: null
    } : value == ScholarshipStatus.contacted ? {
        contacted: null
    } : value == ScholarshipStatus.declined ? {
        declined: null
    } : value == ScholarshipStatus.offered ? {
        offered: null
    } : value == ScholarshipStatus.interested ? {
        interested: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollegeDivision): {
    d1: null;
} | {
    d2: null;
} | {
    d3: null;
} | {
    juco: null;
} | {
    naia: null;
} {
    return value == CollegeDivision.d1 ? {
        d1: null
    } : value == CollegeDivision.d2 ? {
        d2: null
    } : value == CollegeDivision.d3 ? {
        d3: null
    } : value == CollegeDivision.juco ? {
        juco: null
    } : value == CollegeDivision.naia ? {
        naia: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
